/*
 * aleds.c
 *
 *  Created on: FEB 02, 2014
 *      Author: mircea.patras
 *
 *  Description
 *  	Implements LED's application module
 *
 *  History
 *  	FEB 02, 2014 file creation
 */

#include "aleds.h"
#include "stm32f1xx_hal.h"

/**Exported data*/
UINT8 aleds_ledGreenStatus;
UINT16 aleds_ledGreenBlinkTimeMs;

/**
* \brief initialize led's control
*/
void aleds_init( void )
{
	/*XXX : the user led GPIO pin is initialized in gpio.c (generated by CubeMx)*/
	aleds_ledGreenStatus = ALEDS_LED_STATUS_BLINK;
	aleds_ledGreenBlinkTimeMs = 6000; /*ms*/
}

/**
* \brief 	manages led's
*		task		:	10ms with offset
*		description	:	
*/
void aleds_manage( void )
{
	static UINT16 aleds_manage_odd = 0;
	aleds_manage_odd+=10;
	if ( aleds_manage_odd >= 1000 )
	{
		aleds_manage_odd = 0;
	}

	if ( ALEDS_LED_STATUS_ON == aleds_ledGreenStatus ||
			( (ALEDS_LED_STATUS_BLINK == aleds_ledGreenStatus) && (aleds_manage_odd>500) )
		)
	{
		/*led on*/
		HAL_GPIO_WritePin(userLed_GPIO_Port, userLed_Pin, GPIO_PIN_SET);
	}
	else
	{
		/*led off*/
		HAL_GPIO_WritePin(userLed_GPIO_Port, userLed_Pin, GPIO_PIN_RESET);
	}

	if ( aleds_ledGreenBlinkTimeMs > 0 )
	{
		if ( aleds_ledGreenBlinkTimeMs < 20 )
		{
			aleds_ledGreenStatus = ALEDS_LED_STATUS_OFF;
			aleds_ledGreenBlinkTimeMs = 10;
		}
		aleds_ledGreenBlinkTimeMs-=10;
	}

}
