/*
 * abuttons.c
 *
 *  Created on: FEB 28, 2014
 *      Author: mircea.patras
 *
 *  Description
 *  	Implements Buttons's application module
 *
 *  History
 *  	FEB 28, 2014 file creation
 */

#include "abuttons.h"
#include "events.h"
#include "main.h" /*here are defined the gpio pins*/
#include "stm32f1xx_hal.h"

/**Exported data*/

/*gear shift buttons*/
uint8_t btnShiftDw;
uint8_t btnShiftUp;

/**Private date*/
PRIVATE_DATA UINT16 bStartPressedTime;

/**
* \brief initialise led's control
*/
void abuttons_init( void )
{
	/*Note : the button GPIO pin is initialized in gpio.c (generated by CubeMx)*/
	bStartPressedTime = 0;
	/*gear shift buttons*/
	btnShiftDw = 0u;
 	btnShiftUp = 0u;
}

/**
* \brief 	manages led's
*		task		:	100ms
*		description	:	reads status of the input where buttons are connected and updates the status variables
*/
void abuttons_manage( void )
{

	static UINT8 buttonStatusOld = ABUTTONS_STATUS_OFF;

	/*0 == button pressed*/
	if (GPIO_PIN_RESET == HAL_GPIO_ReadPin(userButton_GPIO_Port, userButton_Pin) )
	{/*button pressed*/

		/*detect button status change*/
		if (ABUTTONS_STATUS_OFF == buttonStatusOld)
		{/*button pressed event*/
			MACRO_EV_BSTART_PRESSED
		}
		else
		{/*button was pressed before*/
			if ( bStartPressedTime < 20000 ) bStartPressedTime+=100; /*increment timer and TOP it to 20 seconds*/
		}
		buttonStatusOld = ABUTTONS_STATUS_ON;
	}
	else
	{/*button not pressed*/
		/*detect button status change*/
		if (ABUTTONS_STATUS_ON == buttonStatusOld)
		{/*button released event*/
			MACRO_EV_BSTART_RELEASED
			bStartPressedTime = 0;
		}
		else
		{/*button was released before; TODO see if necessary to count the time button is released*/
		}

		buttonStatusOld = ABUTTONS_STATUS_OFF;
	}

	if (GPIO_PIN_RESET == HAL_GPIO_ReadPin(portShiftGear, pinShiftGearDw) )
	{/*button pressed*/
		btnShiftDw = 1u;
	}
	else
	{
		btnShiftDw = 0u;
	}

	if (GPIO_PIN_RESET == HAL_GPIO_ReadPin(portShiftGear, pinShiftGearUp) )
	{/*button pressed*/
		btnShiftUp = 1u;
	}
	else
	{
		btnShiftUp = 0u;
	}

}

/*returns time while Button Start was pressed*/
UINT16 abuttons_getBStartPressedTime( void )
{
	return bStartPressedTime;
}
